const ingredients = [
  { id: 1, title: "pomodoro" },
  { id: 2, title: "mozzarella" },
  { id: 3, title: "aglio" },
  { id: 4, title: "origano" },
  { id: 5, title: "salame piccante" },
  { id: 6, title: "mozzarella di bufala" },
  { id: 7, title: "gorgonzola" },
  { id: 8, title: "parmigiano" },
  { id: 9, title: "ricotta" },
  { id: 10, title: "funghi" },
];
const pizzas = [
  {
    id: 1,
    name: "Margherita",
    image: "/img/pizze/margherita.webp",
    price: "€ 8.00",
    avaiable: true,
    ingredients: ["pomodoro", "mozzarella"],
  },
  {
    id: 2,
    name: "Marinara",
    image: "/img/pizze/marinara.jpeg",
    price: "€ 6.00",
    avaiable: true,
    ingredients: ["pomodoro", "aglio", "origano"],
  },
  {
    id: 3,
    name: "Diavola",
    image: "/img/pizze/diavola.jpeg",
    price: "€ 7.00",
    avaiable: true,
    ingredients: ["pomodoro", "mozzarella", "salame piccante"],
  },
  {
    id: 4,
    name: "Bufalina",
    image: "/img/pizze/bufalina.jpeg",
    price: "€ 10.00",
    avaiable: true,
    ingredients: ["pomodoro", "mozzarella di bufala"],
  },
  {
    id: 5,
    name: "4 formaggi",
    image: "/img/pizze/4_formaggi.jpeg",
    price: "€ 10.00",
    avaiable: false,
    ingredients: [
      "pomodoro",
      "mozzarella",
      "gorgonzola",
      "parmigiano",
      "ricotta",
    ],
  },
];
export { pizzas, ingredients };
